#+author: conao3
#+date: <2020-03-20 Fri>

[[https://github.com/conao3/keg.el][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/keg.el.png]]
[[https://github.com/conao3/keg.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/keg.el.svg?style=flat-square]]
[[https://github.com/conao3/keg.el/releases][https://img.shields.io/github/tag/conao3/keg.el.svg?style=flat-square]]
[[https://github.com/conao3/keg.el/actions][https://github.com/conao3/keg.el/workflows/Main%20workflow/badge.svg]]
[[https://app.codacy.com/project/conao3/keg.el/dashboard][https://img.shields.io/codacy/grade/62a36f4f04524d5e8c758440e8071c45.svg?logo=codacy&style=flat-square]]
[[https://www.patreon.com/conao3][https://img.shields.io/badge/patreon-become%20a%20patron-orange.svg?logo=patreon&style=flat-square]]
[[https://twitter.com/conao_3][https://img.shields.io/badge/twitter-@conao__3-blue.svg?logo=twitter&style=flat-square]]
[[https://conao3-support.slack.com/join/shared_invite/enQtNjUzMDMxODcyMjE1LWUwMjhiNTU3Yjk3ODIwNzAxMTgwOTkxNmJiN2M4OTZkMWY0NjI4ZTg4MTVlNzcwNDY2ZjVjYmRiZmJjZDU4MDE][https://img.shields.io/badge/chat-on_slack-blue.svg?logo=slack&style=flat-square]]

* Table of Contents
- [[#description][Description]]
- [[#install][Install]]
- [[#usage][Usage]]
  - [[#keg-executable][keg executable]]
    - [[#emacs][emacs]]
    - [[#exec][exec]]
    - [[#files][files]]
    - [[#info][info]]
    - [[#init][init]]
    - [[#install][install]]
    - [[#lint][lint]]
    - [[#load-path][load-path]]
    - [[#version][version]]
    - [[#help][help]]
    - [[#debug][debug]]
  - [[#keg-emacs-package][keg Emacs package]]
  - [[#keg-mode-emacs-major-mode][keg-mode Emacs major-mode]]
- [[#customize][Customize]]
- [[#information][Information]]
  - [[#community][Community]]
  - [[#contribution][Contribution]]
  - [[#migration][Migration]]
  - [[#license][License]]
  - [[#author][Author]]
  - [[#contributors][Contributors]]

* Description
Modern Elisp package development system.

* Install
#+begin_src shell
  git clone https://github.com/conao3/keg.el.git .keg
  PATH=$HOME/.keg/bin:$PATH
#+end_src

#+begin_src emacs-lisp
  (leaf keg :ensure t)
  (leaf keg-mode :ensure t)
#+end_src

* Usage
This repository includes =keg= executable, =keg= Elisp package, =keg-mode= Emacs major-mode.

And [[https://github.com/marketplace/actions/setup-keg][keg-setup]] for GitHub actions is available.

** keg executable
*** emacs
#+begin_src shell
  keg emacs [ARGS...]
#+end_src
Exec Emacs with given args, with the appropriate environment (see =keg exec=).

*** exec
#+begin_src shell
  keg exec [COMMAND] [ARGS...]
#+end_src
Exec command with given args, with the appropriate environment.
- Set =$EMACSLOADPATH= with =$(keg load-path)=

  See [[https://www.gnu.org/software/emacs/manual/html_node/emacs/General-Variables.html#General-Variables][General Variables - Emacs manual]].

*** files
#+begin_src shell
  keg files [PACKAGE]
#+end_src
Show list of files to be packaged.

If package specified, show only list associated with it.

*** info
#+begin_src shell
  keg info [PACKAGE]
#+end_src
Show package info.

If package specified, show only info associated with it.

*** init
#+begin_src shell
  keg init
#+end_src
Create =Keg= file in current directory.

*** install
#+begin_src shell
  keg install [PACKAGE]
#+end_src
Install dependencies in =.keg= sandbox.

If package specified, only install associated with it.

*** lint
#+begin_src shell
  keg lint [PACKAGE]
#+end_src
Lint packages.

If package specified, only lint the specified package.

*** load-path
#+begin_src shell
  keg load-path
#+end_src
Show Emacs appropriate =load-path= same format as =PATH=.
This info is used =keg exec=.

*** version
#+begin_src shell
  keg version
#+end_src
Show =keg= and using =Emacs= version info.

*** help
#+begin_src shell
  keg help
#+end_src
Show subcommand help.

*** debug
#+begin_src shell
  keg debug
#+end_src
Show debug info.


** keg Elisp package
- keg-file-dir :: Get directory path which =Keg= located
- keg-file-path :: Get file path to =Keg= file
- keg-file-read :: Get parsed Sexp readed =Keg= file
- keg-file-read-section :: Get parsed Sexp for specified section.
- keg-install-package :: Install package in =.keg= sandbox
- keg-subcommands :: Get all =keg= subcommands list
- keg-load-path :: Get =load-path= string same format as PATH
- keg-process-environment :: Get appropriate environment value

** keg-mode Emacs major mode
- keg-mode :: Major-mode for =Keg= file

* Customize

* Information
** Community
All feedback and suggestions are welcome!

You can use github issues, but you can also use [[https://conao3-support.slack.com/join/shared_invite/enQtNjUzMDMxODcyMjE1LWUwMjhiNTU3Yjk3ODIwNzAxMTgwOTkxNmJiN2M4OTZkMWY0NjI4ZTg4MTVlNzcwNDY2ZjVjYmRiZmJjZDU4MDE][Slack]]
if you want a more casual conversation.

** Contribution
We welcome PR!

*** Require tools for testing
- cask
  - install via brew
    #+begin_src shell
      brew install cask
    #+end_src

  - manual install
    #+begin_src shell
      cd ~/
      hub clone cask/cask
      export PATH="$HOME/.cask/bin:$PATH"
    #+end_src

*** Running test
Below operation flow is recommended.
#+begin_src shell
  make                              # Install git-hooks in local .git

  git branch [feature-branch]       # Create branch named [feature-branch]
  git checkout [feature-branch]     # Checkout branch named [feature-branch]

  # <edit loop>
  emacs keg.el                      # Edit something you want

  make test                         # Test keg via multi version Emacs
  git commit -am "brabra"           # Commit (auto-run test before commit)
  # </edit loop>

  hub fork                          # Create fork at GitHub
  git push [user] [feature-branch]  # Push feature-branch to your fork
  hub pull-request                  # Create pull-request
#+end_src

** Migration

** License
#+begin_example
  General Public License Version 3 (GPLv3)
  Copyright (c) Naoya Yamashita - https://conao3.com
  https://github.com/conao3/keg.el/blob/master/LICENSE
#+end_example

** Author
- Naoya Yamashita ([[https://github.com/conao3][conao3]])

** Contributors
