name: Main workflow
on:
  push: {branches: [master]}
  pull_request: {branches: [master]}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: purcell/setup-emacs@master
      with:
        version: '28.1'
    - uses: conao3/setup-keg@master
    - name: Run lint
      run: 'make lint'

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - '24.1'
          - '24.2'
          - '24.3'
          - '24.4'
          - '24.5'
          - '25.1'
          - '25.2'
          - '25.3'
          - '26.1'
          - '26.2'
          - '26.3'
          - '27.1'
          - '27.2'
          - '28.1'
          - 'snapshot'
        include:
          - emacs_version: 'snapshot'
            allow_failure: true
          - emacs_version: '24.1'
            only_keg: true
          - emacs_version: '24.2'
            only_keg: true
          - emacs_version: '24.3'
            only_keg: true
          - emacs_version: '24.4'
            only_keg: true
          - emacs_version: '24.5'
            only_keg: true
    steps:
    - uses: actions/checkout@v1
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: conao3/setup-keg@master

    - name: Run tests of keg
      if: matrix.allow_failure != true
      run: 'make test-keg'

    - name: Run tests of keg-mode
      if: matrix.allow_failure != true && matrix.only_keg != true
      run: 'make test-keg-mode'

    - name: Run tests of flycheck-keg
      if: matrix.allow_failure != true && matrix.only_keg != true
      run: 'make test-flycheck-keg'

    - name: Run tests (allow failure)
      if: matrix.allow_failure == true
      run: 'make test || true'
